Repository vektorprogrammet/vektor-frontend, pull requests merged in 2022-11, with the labels that each got.

#202 [VF-61] Add DaisyUI theme
  tailwind.config.js
Labels: PR: Needs Review

#198 VF-73 revert logo back to img tag
  src/components/Header/AppHeader.tsx
  tailwind.config.js
Labels: PR: Good to Merge, hacktoberfest-accepted

#192 [VF-69] daisyUI and dark mode on server staging overview
  src/pages/public/StagingServerOverview/components/ServerOverview.tsx
Labels: PR: Reviewed w/ Comments, hacktoberfest-accepted
